name: flutter_food_app
description: A new Flutter Food Ordering/ Delivery app using Flutter, Firebase and Provider

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  provider: ^6.0.3

  # utils
  badges: ^2.0.3
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  fluttertoast: ^8.0.9
  flutter_easyloading: ^3.0.5
  shimmer: ^2.0.0

  # authentication
  flutter_facebook_auth: ^4.4.1
  flutter_signin_button: ^2.0.0
  firebase_auth: ^3.6.2
  google_sign_in: ^5.4.0

  # storage
  cloud_firestore: ^3.4.3

  # location
  google_maps_flutter: ^2.1.12
  location: ^4.4.0

  # payment
  flutter_sslcommerz: ^2.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

