// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0VH_1gZVjYb_GixaXond4G3n88drqcBw',
    appId: '1:320503605984:web:5732bccaf2d3a9f4743e85',
    messagingSenderId: '320503605984',
    projectId: 'flutter-food-app-4fe68',
    authDomain: 'flutter-food-app-4fe68.firebaseapp.com',
    storageBucket: 'flutter-food-app-4fe68.appspot.com',
    measurementId: 'G-MPPQ7T3C4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgdGFt3LTw9Q5m2ZS90TbFZDdmXJUf_8',
    appId: '1:320503605984:android:b8e3b320e7ef88ae743e85',
    messagingSenderId: '320503605984',
    projectId: 'flutter-food-app-4fe68',
    storageBucket: 'flutter-food-app-4fe68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeFRknPV_ezxMMruTCLZK35igqu1wOOKU',
    appId: '1:320503605984:ios:cca46c1f79598af4743e85',
    messagingSenderId: '320503605984',
    projectId: 'flutter-food-app-4fe68',
    storageBucket: 'flutter-food-app-4fe68.appspot.com',
    iosClientId: '320503605984-k1f8sgacuj6etsnn56puoqbi5amf63r9.apps.googleusercontent.com',
    iosBundleId: 'com.alaminkarno.flutterFoodApp',
  );
}
